import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'

export default function Home({exploreData,cardData}) {
  return (
    <div className=''>
      <Head>
        <title>Anonymouss Aib bnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Banner/>
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className="text-4xl pb-5 font-semibold">Explore Nearby</h2>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map(({img,location,distance})=>(
              <SmallCard
                key={img}
                image={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>

          <div className='flex space-x-4 overflow-x-scroll scrollbar-hide p-3 -ml-3'>
            {cardData?.map(({img,title})=>(
              <MediumCard
                  key={img}
                  image={img}
                  title={title}
              />
            ))}
          </div>
          
        </section>

        <LargeCard 
            img='https://links.papareact.com/4cj'
            title='The Greatest Ourdoors'
            description='Wishlists curated by Airbnb'
            buttonText='Get Inspired'
        />

      </main>
      <Footer/>
      
    </div>
  )
}

export async function getStaticProps(){
  const exploreData = await fetch('https://links.papareact.com/pyp')
  .then((res)=>res.json())

  const cardData = await fetch('https://links.papareact.com/zp1')
  .then((res)=>res.json())
  // console.log(cardData);

  return {
    props:{
      exploreData,
      cardData
    }
  }
}
